use_frameworks!

platform :ios, '8.0'

target 'NSCateGoryKit_Example' do
  pod 'NSCateGoryKit', :path => '../'

  target 'NSCateGoryKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
